name: 🛠 Build and Test on PR to develop or main

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - develop
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 👀 Checkout Code
        uses: actions/checkout@v3

      - name: ✨ Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.9.0

      - name: ⭐️ Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'

      - name: 🏎 Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: 📦 Install Dependencies
        run: |
          pnpm install

      - name: 🚀 Build Project
        run: |
          pnpm build # 빌드 명령어

      - name: 🏁 Finish
        run: |
          echo "🎉 빌드 성공 🎉 "
