name: 🚀 Deploy Storybook to S3 and CloudFront

on:
  push:
    branches:
      - task/#379

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🔔 Check out source code
        uses: actions/checkout@v3

      - name: ✨ Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.9.0

      - name: 🔐 AWS Credential
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: 📂 Install dependencies
        run: |
          pnpm install --filter storybook

      - name: 🏗️ Build project
        run: |
          export CI=false
          pnpm build

      - name: 🚀 Deploy to S3
        run: aws s3 sync ./apps/storybook/storybook-static s3://${{ secrets.AWS_STORYBOOK_BUCKET }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: 📄 Create invalidation in CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_ID }}
          PATHS: '/*'
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
